language: node_js
node_js:
- 9.10.1
notifications:
  email:
    on_failure: change
    on_success: change
addons:
  ssh_known_hosts:
  - 167.99.98.101
branches:
  only:
  - master
  - travis
env:
  global:
  - REMOTE_APP_DIR=/var/www/cooper-front/
  - REMOTE_USER=deploy
  - REMOTE_HOST=167.99.98.101
  - NODE_ENV=testing
  - PORT=80
cache:
  directories:
  - node_modules
install:
- npm install
before_script:
- chmod 600 deploy && mv deploy ~/.ssh/id_rsa
script:
- npm run build
deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch:
    - master
    - travis
before_install:
- openssl aes-256-cbc -K $encrypted_c48c777504c0_key -iv $encrypted_c48c777504c0_iv
  -in deploy.enc -out deploy -d
